export const STATUSES_INIT = {
  0: 'AWAITING',
  3: 'WAIT_QUESTIONNAIRE',
  4: 'QUESTIONNAIRE_DONE',
  5: 'APPROVED',
  6: 'REJECTED'
};

export const RESPOND_STATUSES = {
  AWAITING: STATUSES_INIT[0],
  WAIT_QUESTIONNAIRE: STATUSES_INIT[3],
  QUESTIONNAIRE_DONE: STATUSES_INIT[4],
  APPROVED: STATUSES_INIT[5],
  REJECTED: STATUSES_INIT[6],
}

export const NEW_STATUSES = {
  AWAITING: 0,
  WAIT_QUESTIONNAIRE: 3,
  QUESTIONNAIRE_DONE: 4,
  APPROVED: 5,
  REJECTED: 6,
}
