export * from './main-page';
export * from './not-found';
export * from './create-resume-page';
export * from './create-vacancy-page';
export * from './list-resume-page';
export * from './list-vacancy-page';
export * from './personal-account-page';
export * from './resume-full-page';
export * from './account-setting-page';
