export const ROUTES = [
    '/',
    '/create-resume',
    '/list-resume',
    '/personal-account',
    '/setting',
    '/resume',
    '/vacancy',
    '/create-vacancy',
    '/list-vacancy',
    '/admin',
    '/vacancy/:id',
    '/account-email-confirm',
    '/resume/:id',
];
